export default {
    CD: 1,
    SACD: 2,
    MiniDisc: 3,
    DAT: 4,
    'Digital Media': 5,
    DCC: 6,
    HDCD: 7,
    'USB Flash Drive': 8,
    slotMusic: 9,
    UMD: 10,
    'CD-R': 11,
    '8cm CD': 12,
    'Blu-spec CD': 13,
    'SHM-CD': 14,
    HQCD: 15,
    'Hybrid SACD': 16,
    'CD+G': 17,
    '8cm CD+G': 18,
    'Enhanced CD': 19,
    'Data CD': 20,
    'DTS CD': 21,
    Playbutton: 22,
    'Music Card': 23,
    VinylDisc: 24,
    '3.5" Floppy Disk': 25,
    'SHM-SACD': 26,
    CED: 27,
    'Copy Control CD': 28,
    'SD Card': 29,
    'Hybrid SACD (CD layer)': 30,
    'Hybrid SACD (SACD layer)': 31,
    PlayTape: 32,
    HiPac: 33,
    'Floppy Disk': 34,
    'Zip Disk': 35,
    'VinylDisc (CD side)': 36,
} as Record<string, number>;
